services:

    documentlanding.sdk_manager:
        class: DocumentLanding\SdkBundle\Service\SdkManager
        arguments: [ %DocumentLandingSdkBundleConfig%, @event_dispatcher, %kernel.bundles%, %kernel.root_dir%, %kernel.environment%, @router ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onUrlParse }
